const lostReportPatterns = [
    /my name is\s+([a-z\s]+?)\s*ltp\s*(?:is\s*)?(\d{5})[\W\s]*(?:what is|tell|give) my report status/i,
    /my name is\s+([a-z\s]+?)\s*ltp\s*(?:is\s*)?(\d{5})[\W\s]*(?:what is|tell) my report status/i,
    /my name is\s+([a-z\s]+?)[\W\s]*(?:what is|tell) my report status/i,
    /has\s+([a-z\s]+?)\s*ltp\s*(?:is\s*)?(\d{5})[\W\s]*reported/i,
    /name\s+([a-z\s]+?)\s*ltp\s*(?:is\s*)?(\d{5})[\W\s]*/i,
    /i am\s+([a-z\s]+?)\s*ltp\s*(?:is\s*)?(\d{5})[\W\s]*have i reported/i,
    /([a-z\s]+?)\s*ltp\s*(?:is\s*)?(\d{5})[\W\s]*/i,
    /name\s+([a-z\s]+?)\s*ltp\s*(?:is\s*)?(\d{5})/i,
    /i am\s+([a-z\s]+?)\s*ltp\s*(?:is\s*)?(\d{5})[\W\s]*have i reported/i,
    /i am\s+([a-z\s]+?),?\s*have i reported any (?:lost\s+)?luggage\s*ltp\s*(?:is\s*)?(\d{5})/i,
    /i am\s+([a-z\s]+?),?\s*did i file a report\s*(?:under\s*)?ltp\s*(?:is\s*)?(\d{5})/i,
    /i'm\s+([a-z\s]+?),?\s*did i submit a report for (?:lost\s+)?luggage\s*(?:under\s*)?ltp\s*(?:is\s*)?(\d{5})/i,
    /has\s+([a-z\s]+?)\s*ltp\s*(?:is\s*)?(\d{5})[\W\s]*reported/i,
    /have\s+([a-z\s]+?)\s*ltp\s*(?:is\s*)?(\d{5})[\W\s]*reported/i,
    /is there (?:any\s*)?report\s*([a-z\s]+?)\s*ltp\s*(?:is\s*)?(\d{5})/i,
    /is there a record of (?:lost\s+)?luggage\s*([a-z\s]+?)\s*ltp\s*(?:is\s*)?(\d{5})/i,
    /was a report filed\s*([a-z\s]+?)\s*ltp\s*(?:is\s*)?(\d{5})/i,
    /did\s+([a-z\s]+?)\s*file a report\s*ltp\s*(?:is\s*)?(\d{5})/i,
    /can you find a report for (?:lost\s+)?luggage\s*([a-z\s]+?)\s*ltp\s*(?:is\s*)?(\d{5})/i,
    /is there a (?:lost\s+)?luggage report\s*with\s*([a-z\s]+?)\s*ltp\s*(?:is\s*)?(\d{5})/i,
    /confirm if a report was made\s*([a-z\s]+?)\s*ltp\s*(?:is\s*)?(\d{5})/i,
    /find a (?:lost\s+)?luggage report\s*([a-z\s]+?)\s*ltp\s*(?:is\s*)?(\d{5})/i,
    /does\s+([a-z\s]+?)\s*have a (?:lost\s+)?luggage report\s*ltp\s*(?:is\s*)?(\d{5})/i,
    /i am\s+([a-z\s]+?),\s*have i reported any (?:lost\s+)?luggage\s*ltp\s*(?:is\s*)?(\d{5})/i,
    /my name is\s+([a-z\s]+?),\s*did i submit a report for (?:lost\s+)?luggage\s*ltp\s*(?:is\s*)?(\d{5})/i,
    /i'm\s+([a-z\s]+?),\s*any (?:lost\s+)?luggage report\s*ltp\s*(?:is\s*)?(\d{5})/i,
    /check for report\s*([a-z\s]+?)\s*ltp\s*(?:is\s*)?(\d{5})/i,
    /lost luggage report,\s*ltp\s*(?:is\s*)?(\d{5}),\s*name\s+([a-z\s]+)/i,
];
